sudo: required
addons:
  firefox: latest
  chrome: stable
os:
  - linux
dist: xenial
services:
  - xvfb
language: node_js
node_js:
- '8'
before_install:
- npm set progress false
install:
- npm install 
script:
- npm run lint
- npm run build:dnd
- npm run test:dnd
after_success:
- npm run codecov