sudo: required
addons:
  firefox: latest
  chrome: stable
os:
- linux
language: node_js
node_js:
- '8'
before_install:
- npm set progress false
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install 
script:
- npm run lint:all
- npm run build:dnd
- npm run test:dnd
after_success:
- npm run codecov